name: uas_flutter_absen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  file_picker: ^7.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.5
  google_sign_in: ^6.1.6
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  syncfusion_flutter_datepicker: ^19.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
