// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzuGFfM0_zioBAh6l6hZEnXYd-NuQkZRo',
    appId: '1:105167511878:web:49f802a65fe9c6567fc547',
    messagingSenderId: '105167511878',
    projectId: 'uas-smt2-flutter',
    authDomain: 'uas-smt2-flutter.firebaseapp.com',
    storageBucket: 'uas-smt2-flutter.appspot.com',
    measurementId: 'G-RLSRRQZQME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Vr4D506iMUkQ6Rzj1Y1rEtLRTnd7pSw',
    appId: '1:105167511878:android:baa1283cb10169367fc547',
    messagingSenderId: '105167511878',
    projectId: 'uas-smt2-flutter',
    storageBucket: 'uas-smt2-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqjJ3CwNfavPyskW3KiNliwyEmS1O7hY',
    appId: '1:105167511878:ios:63236f1ec1c0e1087fc547',
    messagingSenderId: '105167511878',
    projectId: 'uas-smt2-flutter',
    storageBucket: 'uas-smt2-flutter.appspot.com',
    iosBundleId: 'com.smkmq.ujian.uasFlutterAbsen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoqjJ3CwNfavPyskW3KiNliwyEmS1O7hY',
    appId: '1:105167511878:ios:63236f1ec1c0e1087fc547',
    messagingSenderId: '105167511878',
    projectId: 'uas-smt2-flutter',
    storageBucket: 'uas-smt2-flutter.appspot.com',
    iosBundleId: 'com.smkmq.ujian.uasFlutterAbsen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzuGFfM0_zioBAh6l6hZEnXYd-NuQkZRo',
    appId: '1:105167511878:web:b982a8bd056cff027fc547',
    messagingSenderId: '105167511878',
    projectId: 'uas-smt2-flutter',
    authDomain: 'uas-smt2-flutter.firebaseapp.com',
    storageBucket: 'uas-smt2-flutter.appspot.com',
    measurementId: 'G-LQY74355L6',
  );
}
